apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-service
    app: microservice
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
  selector:
     app: gateway
     type: microservice