apiVersion: v1
kind: Service
metadata:
  name: microservice-seguridad-service
  labels:
    name: microservice-seguridad-service
    app: microservice
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: microservice-seguridad
    type: microservice