apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo:jammy
      #command:
      #- /bin/bash
      #- -c
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "root"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "example"
      ports:
        - containerPort: 27017